name: Deploy GitHub Pages Site

on:
  push:
  schedule:
    - cron: '0 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build
      - run: git config --global user.email "Moritz.Hayden@gmail.com"
      - run: git config --global user.name "MoritzHayden"
      - run: git remote add origin git@github.com:MoritzHayden/MoritzHayden.github.io.git
      - run: npm run deploy
