name: CI/CD

on:
  push:
  schedule:
    - cron: '0 5 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout main
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}

    - name: Checkout gh-pages
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Create CNAME
      run: touch CNAME

    - name: Populate CNAME
      run: printf "www.haydenmoritz.com\n" >> CNAME

    - name: Commit CNAME
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: gh-pages
        commit_message: Add CNAME
        file_pattern: CNAME
